---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Secret
metadata:
  namespace: app  
  name: dev-bucket-credentials
type: Opaque
stringData:
  accesskey: dev-bucket
  secretkey: dev-bucket123  
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  namespace: app
  name: dev-bucket
spec:
  interval: 1m
  provider: generic
  bucketName: dev-bucket
  endpoint: dev-bucket.dev-bucket.svc.cluster.local:9000
  region: us-east-1
  insecure: true
  secretRef:
    name: dev-bucket-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  namespace: app
  name: dev-ks
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: Bucket
    name: dev-bucket
  path: ./
